/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "outline-variant": "#c3c6d7",
        "surface-container-low": "#f2f4f6",
        "on-surface": "#191c1e",
        "surface": "#f7f9fb",
        "secondary": "#4a5d90",
        "surface-tint": "#0056d2",
        "error-container": "#ffdad6",
        "secondary-fixed": "#dae2ff",
        "secondary-fixed-dim": "#b2c5ff",
        "primary-fixed-dim": "#b2c5ff",
        "outline": "#737786",
        "on-tertiary-container": "#fffbff",
        "primary-fixed": "#dae2ff",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#e0e3e5",
        "on-background": "#191c1e",
        "tertiary-fixed": "#ffdbc7",
        "secondary-container": "#b2c5ff",
        "on-error": "#ffffff",
        "error": "#ba1a1a",
        "surface-bright": "#f7f9fb",
        "inverse-on-surface": "#eff1f3",
        "inverse-primary": "#b2c5ff",
        "surface-dim": "#d8dadc",
        "background": "#f7f9fb",
        "on-primary-container": "#fefcff",
        "surface-container-high": "#e6e8ea",
        "tertiary-container": "#b95a00",
        "on-primary-fixed-variant": "#0040a1",
        "surface-container": "#eceef0",
        "on-primary-fixed": "#001847",
        "on-secondary-fixed-variant": "#314576",
        "primary-container": "#2e6dec",
        "on-surface-variant": "#424654",
        "on-tertiary-fixed": "#311300",
        "tertiary-fixed-dim": "#ffb688",
        "on-tertiary-fixed-variant": "#733500",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#3d5183",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#001847",
        "primary": "#0054cd",
        "tertiary": "#934600",
        "surface-variant": "#e0e3e5",
        "inverse-surface": "#2d3133"
      },
      fontFamily: {
        "sans": ["Inter", "sans-serif"],
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
